export const CHECK_NODE_STATUS_START = 'CHECK_NODE_STATUS_START';
export const CHECK_NODE_STATUS_SUCCESS = 'CHECK_NODE_STATUS_SUCCESS';
export const CHECK_NODE_STATUS_FAILURE = 'CHECK_NODE_STATUS_FAILURE';
export const ADD_BLOCK_START = 'ADD_BLOCK_START';
export const ADD_BLOCK_SUCCESS = 'ADD_BLOCK_SUCCESS';
export const ADD_BLOCK_FAILURE = 'ADD_BLOCK_FAILURE';
